# Generated by Django 4.2.7 on 2026-06-15 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('is_demo', models.BooleanField(default=False)),
                ('scan_image', models.ImageField(blank=True, null=True, upload_to='scans/%Y/%m/%d/')),
                ('skin_tone', models.CharField(choices=[('fair', 'Fair'), ('light', 'Light'), ('medium', 'Medium'), ('tan', 'Tan'), ('deep', 'Deep')], default='medium', max_length=20)),
                ('undertone', models.CharField(choices=[('warm', 'Warm'), ('cool', 'Cool'), ('neutral', 'Neutral'), ('olive', 'Olive')], default='neutral', max_length=20)),
                ('face_shape', models.CharField(choices=[('oval', 'Oval'), ('round', 'Round'), ('square', 'Square'), ('heart', 'Heart'), ('oblong', 'Oblong')], default='oval', max_length=20)),
                ('skin_type', models.CharField(choices=[('oily', 'Oily'), ('dry', 'Dry'), ('combination', 'Combination'), ('normal', 'Normal')], default='normal', max_length=20)),
                ('skin_age', models.IntegerField(default=25)),
                ('real_age', models.IntegerField(default=25)),
                ('harmony_score', models.IntegerField(default=75)),
                ('hydration_score', models.IntegerField(default=60)),
                ('pigmentation_score', models.IntegerField(default=30)),
                ('acne_score', models.IntegerField(default=20)),
                ('aging_score', models.IntegerField(default=25)),
                ('elasticity_score', models.IntegerField(default=65)),
                ('hf_acne_severity', models.CharField(default='none', max_length=20)),
                ('hf_skin_type', models.CharField(default='normal', max_length=20)),
                ('hf_undertone', models.CharField(default='neutral', max_length=20)),
                ('hf_acne_confidence', models.FloatField(default=0.0)),
                ('hf_skin_type_confidence', models.FloatField(default=0.0)),
                ('hf_undertone_confidence', models.FloatField(default=0.0)),
                ('hf_acne_raw', models.TextField(blank=True)),
                ('hf_skin_type_raw', models.TextField(blank=True)),
                ('hf_undertone_raw', models.TextField(blank=True)),
                ('facial_zones', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detected_concerns', models.ManyToManyField(blank=True, related_name='scans', to='products.skinconcern')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
