# Generated by Django 4.2.7 on 2026-06-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='face_shape',
            field=models.CharField(choices=[('oval', 'Oval'), ('round', 'Round'), ('square', 'Square'), ('heart', 'Heart'), ('oblong', 'Oblong'), ('rectangle', 'Rectangle'), ('diamond', 'Diamond'), ('triangle', 'Triangle')], default='oval', max_length=20),
        ),
    ]
