# Generated by Django 4.2.7 on 2026-06-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_add_face_shape_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other / Prefer not to say')], default='female', max_length=10),
        ),
    ]
