# Generated by Django 4.2.7 on 2026-07-08 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_scanresult_qa_fields'),
        ('scanner', '0003_add_gender_to_scanresult'),
    ]

    operations = [
    ]
