# Generated by Django 4.2.7 on 2026-07-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_progresscomparison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresscomparison',
            name='acne_delta',
            field=models.IntegerField(default=0, help_text='Positive = more acne (worse); negative = improvement'),
        ),
        migrations.AlterField(
            model_name='progresscomparison',
            name='aging_delta',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='progresscomparison',
            name='ai_recommendation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='progresscomparison',
            name='days_between',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='progresscomparison',
            name='harmony_delta',
            field=models.IntegerField(default=0),
        ),
    ]
