# Generated by Django 4.2.7 on 2026-06-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('cleanser', 'Cleanser'), ('toner', 'Toner'), ('essence', 'Essence'), ('serum', 'Serum'), ('ampoule', 'Ampoule'), ('moisturizer', 'Moisturizer'), ('cream', 'Cream'), ('emulsion', 'Emulsion'), ('sunscreen', 'Sunscreen'), ('mask', 'Mask'), ('eye_cream', 'Eye Cream'), ('exfoliator', 'Exfoliator'), ('oil', 'Oil'), ('mist', 'Mist'), ('treatment', 'Treatment'), ('foundation', 'Foundation'), ('concealer', 'Concealer'), ('powder', 'Powder'), ('blush', 'Blush'), ('bronzer', 'Bronzer'), ('highlighter', 'Highlighter'), ('eyeshadow', 'Eyeshadow'), ('eyeliner', 'Eyeliner'), ('mascara', 'Mascara'), ('lipstick', 'Lipstick'), ('lip_gloss', 'Lip Gloss'), ('lip_liner', 'Lip Liner')], max_length=50)),
                ('product_range', models.CharField(choices=[('korean', 'K-Beauty'), ('makeup', 'Makeup'), ('treatment', 'Treatment')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('key_ingredients', models.TextField(blank=True, help_text='Comma-separated list of key ingredients')),
                ('full_ingredients', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('image_url', models.URLField(blank=True)),
                ('suitable_for_skin_types', models.JSONField(blank=True, default=list)),
                ('targets', models.JSONField(blank=True, default=list, help_text='List of concern slugs this product addresses')),
                ('shades_available', models.JSONField(blank=True, default=list, help_text='List of shade objects with name and hex color')),
                ('undertone_match', models.CharField(blank=True, choices=[('warm', 'Warm'), ('cool', 'Cool'), ('neutral', 'Neutral'), ('olive', 'Olive')], max_length=20)),
                ('skin_tone_match', models.CharField(blank=True, choices=[('fair', 'Fair'), ('light', 'Light'), ('medium', 'Medium'), ('tan', 'Tan'), ('deep', 'Deep')], max_length=20)),
                ('coverage', models.CharField(blank=True, max_length=50)),
                ('finish', models.CharField(blank=True, max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['brand', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkinConcern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Skin Concern',
                'verbose_name_plural': 'Skin Concerns',
                'ordering': ['name'],
            },
        ),
    ]
