# Generated by Django 4.2.7 on 2026-06-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cleanser', 'Cleanser'), ('toner', 'Toner'), ('essence', 'Essence'), ('serum', 'Serum'), ('ampoule', 'Ampoule'), ('moisturizer', 'Moisturizer'), ('cream', 'Cream'), ('emulsion', 'Emulsion'), ('sunscreen', 'Sunscreen'), ('mask', 'Mask'), ('eye_cream', 'Eye Cream'), ('exfoliator', 'Exfoliator'), ('oil', 'Oil'), ('mist', 'Mist'), ('treatment', 'Treatment'), ('primer', 'Primer'), ('foundation', 'Foundation'), ('concealer', 'Concealer'), ('setting_powder', 'Setting Powder'), ('powder', 'Powder'), ('blush', 'Blush'), ('bronzer', 'Bronzer'), ('highlighter', 'Highlighter'), ('eyeshadow', 'Eyeshadow'), ('eyeshadow_palette', 'Eyeshadow Palette'), ('eyeliner', 'Eyeliner'), ('mascara', 'Mascara'), ('lipstick', 'Lipstick'), ('lip_gloss', 'Lip Gloss'), ('lip_liner', 'Lip Liner')], max_length=50),
        ),
    ]
