# Generated by Django 4.2.7 on 2026-07-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_range',
            field=models.CharField(choices=[('korean', 'K-Beauty'), ('makeup', 'Makeup'), ('treatment', 'Treatment'), ('ayurvedic', 'Ayurvedic'), ('pharmacy', 'Pharmacy')], max_length=50),
        ),
    ]
