# Generated by Django 4.2.7 on 2026-07-12 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scanner', '0006_alter_progresscomparison_acne_delta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('score_day0', models.IntegerField(blank=True, null=True)),
                ('score_day14', models.IntegerField(blank=True, null=True)),
                ('score_day30', models.IntegerField(blank=True, null=True)),
                ('score_day60', models.IntegerField(blank=True, null=True)),
                ('score_day90', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan_day0', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestone_day0', to='scanner.scanresult')),
                ('scan_day14', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestone_day14', to='scanner.scanresult')),
                ('scan_day30', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestone_day30', to='scanner.scanresult')),
                ('scan_day60', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestone_day60', to='scanner.scanresult')),
                ('scan_day90', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestone_day90', to='scanner.scanresult')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scan_milestone', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scan Milestone',
            },
        ),
        migrations.CreateModel(
            name='WeeklyCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField(help_text='Weeks since the user started (1-indexed)')),
                ('week_start', models.DateField()),
                ('overall_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
                ('hydration_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
                ('acne_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, help_text='5 = no acne, 1 = very bad')),
                ('brightness_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
                ('products_used', models.JSONField(blank=True, default=list)),
                ('new_concerns', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('has_selfie', models.BooleanField(default=False)),
                ('overall_delta', models.SmallIntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weekly Check-in',
                'ordering': ['-week_number'],
                'unique_together': {('user', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='DailyRoutineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('am_done', models.BooleanField(default=False)),
                ('am_notes', models.CharField(blank=True, max_length=300)),
                ('am_logged_at', models.DateTimeField(blank=True, null=True)),
                ('pm_done', models.BooleanField(default=False)),
                ('pm_notes', models.CharField(blank=True, max_length=300)),
                ('pm_logged_at', models.DateTimeField(blank=True, null=True)),
                ('water_glasses', models.PositiveSmallIntegerField(default=0)),
                ('spf_applied', models.BooleanField(default=False)),
                ('skin_rating', models.PositiveSmallIntegerField(default=3, help_text='User self-rated skin condition 1 (poor) – 5 (great)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_routine_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Routine Log',
                'ordering': ['-log_date'],
                'unique_together': {('user', 'log_date')},
            },
        ),
    ]
