# Generated by Django 4.2.7 on 2026-06-21 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_id', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(help_text='Brief title of requirement', max_length=200)),
                ('custom_product', models.TextField(blank=True, help_text='Describe product if not in catalog (brand, name, shade…)')),
                ('requirement_notes', models.TextField(blank=True, help_text='Special instructions, skin concerns, any details')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address_line1', models.CharField(max_length=250)),
                ('address_line2', models.CharField(blank=True, max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('processing', 'Processing'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('employee_notes', models.TextField(blank=True, help_text='Internal notes by employee/admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Employee handling this requirement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requirements', to=settings.AUTH_USER_MODEL)),
                ('linked_order', models.ForeignKey(blank=True, help_text='Order created to fulfil this requirement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='orders.order')),
                ('products', models.ManyToManyField(blank=True, help_text='Products user wants', related_name='requirements', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Requirement',
                'verbose_name_plural': 'User Requirements',
                'ordering': ['-created_at'],
            },
        ),
    ]
