# Generated by Django 4.2.7 on 2026-07-13 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hair', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hairsession',
            name='age',
        ),
    ]
