# Generated by Django 4.2.7 on 2026-06-22 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('password_reset', 'Password Reset'), ('welcome', 'Welcome Email'), ('notification', 'Notification'), ('other', 'Other')], default='other', max_length=32)),
                ('recipient', models.EmailField(help_text='Recipient email address.', max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body_preview', models.TextField(blank=True, help_text='First 500 chars of the email body (for admin preview).')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='sent', max_length=16)),
                ('error_msg', models.TextField(blank=True, help_text='Error detail if sending failed.')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='The user this email was sent to (if known).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
