# Generated by Django 4.2.7 on 2026-07-12 09:34

import apps.coupons.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.coupons.models._gen_code, max_length=30, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('coupon_type', models.CharField(choices=[('percent', 'Percentage Off'), ('fixed', 'Fixed Amount Off'), ('free_ship', 'Free Shipping')], default='percent', max_length=12)),
                ('discount_value', models.DecimalField(decimal_places=2, default=10, help_text='Percentage (e.g. 15 = 15%) or fixed INR amount', max_digits=8)),
                ('max_discount_inr', models.DecimalField(blank=True, decimal_places=2, help_text='Cap for percentage coupons (leave blank for no cap)', max_digits=8, null=True)),
                ('scope', models.CharField(choices=[('all', 'All Products'), ('korean', 'Korean Range Only'), ('makeup', 'Makeup Only'), ('ayurvedic', 'Ayurvedic Only'), ('pharmacy', 'Pharmacy Only')], default='all', max_length=12)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, help_text='Minimum cart value to activate this coupon', max_digits=10)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Total uses allowed (blank = unlimited)', null=True)),
                ('max_uses_per_user', models.PositiveSmallIntegerField(default=1, help_text='Times a single user can use this coupon')),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('tier_required', models.CharField(blank=True, help_text='Leave blank for all tiers. Set "medium" or "vip" to restrict.', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_referral', models.BooleanField(default=False, help_text='Generated automatically from referral system')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupon',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref', models.CharField(blank=True, max_length=30)),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='coupons.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
    ]
