# Generated by Django 4.2.7 on 2026-07-04 08:20

import apps.memberships.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('normal', 'Normal'), ('medium', 'Medium'), ('vip', 'VIP')], default='normal', max_length=10)),
                ('referral_code', models.CharField(default=apps.memberships.models._gen_referral_code, max_length=12, unique=True)),
                ('loyalty_points', models.PositiveIntegerField(default=0)),
                ('tier_updated_at', models.DateTimeField(auto_now_add=True)),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
                ('staff_role', models.CharField(choices=[('none', 'None'), ('marketing', 'Marketing'), ('admin', 'Admin')], default='none', max_length=12)),
                ('admin_override_tier', models.CharField(blank=True, choices=[('normal', 'Normal'), ('medium', 'Medium'), ('vip', 'VIP')], default='', max_length=10)),
                ('admin_override_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
        migrations.CreateModel(
            name='TierAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_tier', models.CharField(max_length=10)),
                ('new_tier', models.CharField(max_length=10)),
                ('points_deducted', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(default='manual', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='memberships.userprofile')),
            ],
            options={
                'verbose_name': 'Tier Audit Log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('revoked', 'Revoked')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to='memberships.userprofile')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='memberships.userprofile')),
            ],
            options={
                'verbose_name': 'Referral Log',
            },
        ),
    ]
