# Generated by Django 4.2.7 on 2026-07-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_step',
            field=models.CharField(choices=[('profile_setup', 'Profile Setup'), ('scan', 'Selfie Scan'), ('quiz', 'Smart Quiz'), ('done', 'Completed')], default='profile_setup', max_length=20),
        ),
    ]
