# Generated by Django 4.2.7 on 2026-07-11 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('age', models.PositiveSmallIntegerField(default=25)),
                ('age_group', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('climate', models.CharField(blank=True, max_length=30)),
                ('occupation', models.CharField(blank=True, max_length=20)),
                ('skin_concerns', models.JSONField(default=list)),
                ('face_feel_after_wash', models.CharField(blank=True, max_length=30)),
                ('oiliness_timing', models.CharField(blank=True, max_length=30)),
                ('pores_visible', models.CharField(blank=True, max_length=20)),
                ('skin_peels', models.CharField(blank=True, max_length=20)),
                ('has_pimples', models.BooleanField(default=False)),
                ('has_whiteheads', models.BooleanField(default=False)),
                ('has_blackheads', models.BooleanField(default=False)),
                ('has_painful_acne', models.BooleanField(default=False)),
                ('has_acne_scars', models.BooleanField(default=False)),
                ('has_redness', models.BooleanField(default=False)),
                ('has_itching', models.BooleanField(default=False)),
                ('has_burning', models.BooleanField(default=False)),
                ('has_cystic_acne', models.BooleanField(default=False)),
                ('acne_severity', models.CharField(choices=[('none', 'No Acne'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='none', max_length=20)),
                ('pigmentation_concerns', models.JSONField(default=list)),
                ('sensitivity_symptoms', models.JSONField(default=list)),
                ('aging_concerns', models.JSONField(default=list)),
                ('hydration_issues', models.JSONField(default=list)),
                ('water_intake', models.CharField(blank=True, max_length=20)),
                ('sleep_hours', models.CharField(blank=True, choices=[('lt6', 'Less than 6 hours'), ('6to8', '6–8 hours'), ('gt8', 'More than 8 hours')], max_length=20)),
                ('stress_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('exercise', models.CharField(blank=True, max_length=20)),
                ('smoking', models.BooleanField(default=False)),
                ('alcohol', models.CharField(blank=True, max_length=20)),
                ('food_habits', models.JSONField(default=list)),
                ('morning_cleanser', models.BooleanField(default=False)),
                ('moisturizer', models.BooleanField(default=False)),
                ('sunscreen', models.BooleanField(default=False)),
                ('night_routine', models.BooleanField(default=False)),
                ('uses_retinol', models.BooleanField(default=False)),
                ('uses_vitamin_c', models.BooleanField(default=False)),
                ('uses_niacinamide', models.BooleanField(default=False)),
                ('uses_exfoliation', models.BooleanField(default=False)),
                ('wears_foundation', models.BooleanField(default=False)),
                ('wears_concealer', models.BooleanField(default=False)),
                ('wears_primer', models.BooleanField(default=False)),
                ('wears_setting_spray', models.BooleanField(default=False)),
                ('brush_cleaning_freq', models.CharField(blank=True, max_length=30)),
                ('sleeps_with_makeup', models.CharField(blank=True, max_length=20)),
                ('is_pregnant', models.BooleanField(default=False)),
                ('is_breastfeeding', models.BooleanField(default=False)),
                ('has_pcos', models.BooleanField(default=False)),
                ('has_thyroid', models.BooleanField(default=False)),
                ('has_diabetes', models.BooleanField(default=False)),
                ('on_skin_medication', models.BooleanField(default=False)),
                ('uses_isotretinoin', models.BooleanField(default=False)),
                ('uses_steroids', models.BooleanField(default=False)),
                ('known_allergies', models.CharField(blank=True, max_length=200)),
                ('medical_notes', models.TextField(blank=True)),
                ('skin_type_result', models.CharField(blank=True, choices=[('oily', 'Oily'), ('dry', 'Dry'), ('combination', 'Combination'), ('normal', 'Normal'), ('sensitive', 'Sensitive')], max_length=20)),
                ('primary_concern', models.CharField(blank=True, max_length=60)),
                ('recommended_routine', models.JSONField(default=dict)),
                ('ai_summary', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skin_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skin Session',
                'ordering': ['-created_at'],
            },
        ),
    ]
