# Generated by Django 4.2.30 on 2026-07-08 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeloginlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'User Login Log', 'verbose_name_plural': 'User Login Logs'},
        ),
    ]
