# Generated by Django 4.2.7 on 2026-07-08 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=80)),
                ('icon', models.CharField(max_length=10)),
                ('color_class', models.CharField(max_length=30)),
                ('points', models.PositiveSmallIntegerField(default=5)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ReferralClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('converted', models.BooleanField(default=False)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('points_earned', models.PositiveSmallIntegerField(default=0)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='diagnostic.habitcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Habit Log',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('selected_categories', models.JSONField(default=list)),
                ('skin_type', models.CharField(blank=True, max_length=30)),
                ('concern_1', models.CharField(blank=True, max_length=60)),
                ('concern_2', models.CharField(blank=True, max_length=60)),
                ('concern_3', models.CharField(blank=True, max_length=60)),
                ('budget', models.CharField(blank=True, max_length=20)),
                ('water_intake', models.PositiveSmallIntegerField(default=5)),
                ('sleep_hours', models.PositiveSmallIntegerField(default=6)),
                ('stress_level', models.PositiveSmallIntegerField(default=5)),
                ('recommended_tier', models.CharField(choices=[('normal', 'Normal'), ('medium', 'Medium'), ('vip', 'VIP')], default='normal', max_length=10)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diagnostic Session',
                'ordering': ['-created_at'],
            },
        ),
    ]
