# Generated by Django 4.2.7 on 2026-07-11 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diagnostic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartDiagSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('primary_goal', models.CharField(blank=True, max_length=40)),
                ('answers', models.JSONField(default=dict)),
                ('analysis', models.JSONField(default=dict)),
                ('severity', models.CharField(blank=True, max_length=20)),
                ('top_concern_cat', models.CharField(blank=True, max_length=40)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smart_diag_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Smart Diagnostic Session',
                'ordering': ['-created_at'],
            },
        ),
    ]
