# Generated by Django 4.2.7 on 2026-07-12 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('scan_reminder', 'Scan Reminder'), ('progress_check', 'Progress Check-in'), ('tier_upgrade', 'Tier Upgrade'), ('tier_expiry', 'Tier Expiry Warning'), ('order_update', 'Order Update'), ('points_earned', 'Points Earned'), ('routine_reminder', 'Routine Reminder'), ('weekly_checkin', 'Weekly Check-in'), ('system', 'System Message'), ('achievement', 'Achievement Unlocked')], default='system', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('icon', models.CharField(default='🔔', max_length=10)),
                ('action_url', models.CharField(blank=True, max_length=300)),
                ('action_label', models.CharField(blank=True, max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
