# Generated by Django 4.2.7 on 2026-06-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='mode',
            field=models.CharField(choices=[('doctor', 'AI Doctor'), ('makeup', 'Makeup'), ('kbeauty', 'K-Beauty')], default='doctor', max_length=20),
        ),
    ]
