# Generated by Django 4.2.7 on 2026-07-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_add_mode_to_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_vip_session',
            field=models.BooleanField(default=False),
        ),
    ]
